baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coopdevs.org" # the base hostname & protocol for your site, e.g. http://example.com
title: "Coopdevs"
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin configuration
languages: ["ca", "es"]
exclude_from_localizations: ["javascript", "images", "css"]

# Not used by jekyll-multiple-languages-plugin configuration but it makes it
# a bit more evident what's the default language picked by this plugin
default_locale: 'ca'

friends:
  - name: 'Open Food Network'
    url: 'https://openfoodnetwork.org/'
    logo_url: '/assets/img/friends/ofn.png'
  - name: 'Som Connexió'
    url: 'http://somconnexio.coop'
    logo_url: '/assets/img/friends/som_connexio.png'
  - name: 'Asociación para el Desarrollo de los Bancos de Tiempo'
    url: 'http://adbdt.org/'
    logo_url: '/assets/img/friends/adbdt.jpg'
  - name: 'Xarxa Economia Solidària'
    url: 'http://xes.cat/'
    logo_url: '/assets/img/friends/XES.jpg'
  - name: 'Balanç Social'
    url: 'https://ensenyaelcor.org'
    logo_url: '/assets/img/friends/balancsocial.jpg'
  - name: 'Pam a Pam'
    url: 'https://pamapam.org'
    logo_url: '/assets/img/friends/pamapam.png'
  - name: 'La Comunificadora'
    url: 'http://emprenedoria.barcelonactiva.cat/emprenedoria/cat/programes/la-comunificadora.jsp'
    logo_url: '/assets/img/friends/la_comunificadora2.png'
  - name: 'La Lleialtat Santsenca'
    url: 'https://www.lleialtat.cat/'
    logo_url: '/assets/img/friends/lleialtat.png'
  - name: 'Aracoop'
    url: 'http://aracoop.coop/'
    logo_url: '/assets/img/friends/aracoop.png'
    name: 'La borda'
    url: 'http://www.laborda.coop'
    logo_url: '/assets/img/friends/laborda.png'
